config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'articles/my_articles'
  resources :comments

  resources :articles
  resources :categories

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

	has_many :comments
	has_many :article_categories
    has_many :categories,through: :article_categories
    belongs_to :user

    validates_presence_of :title
	validates_presence_of :body


end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article
	belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles , through: :article_categories
	validates_presence_of :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :article
	belongs_to :user

	validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :articles
	has_many :comments
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!

	def index
		@article = Article.all
	end
	def new 
		@article = Article.new 
	end

	def create
		@article = Article.new(article_param)
		@article.user_id = current_user.id
		#@article.published_on = DateTime.now
		if @article.save
			redirect_to articles_path , notice: "Successfully created article"
		else
			render action:"new"
		end
	end

	def show
	begin
	  @article = Article.find(params[:id])
	  @comments = @article.comments
	  @comment = Comment.new
	rescue ActiveRecord::RecordNotFound
		redirect_to articles_path, notice:"Record Not Found"
	end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(article_param)
			redirect_to article_path(@article), notice: "Successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@comments = @article.comments
		@comments.destroy_all
		@article.destroy
		redirect_to articles_path
	end

	def my_articles
		@myarticles = Article.where('user_id=?',current_user.id)
	end

	private

	def article_param
		params[:article].permit(:title, :body, category_ids: [])
	end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index 
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_param)
		if @category.save
			redirect_to categories_path
		else
			render action: "new"
		end
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update_attributes(category_param)
			redirect_to categories_path, notice: "Successfully updated"
		else
			render action: "edit"
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end



	private

	def category_param
		params[:category].permit(:name)
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@article = Article.find(params[:comment][:article_id])
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to article_path(@comment.article_id)
		else
			render action: "new"
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to article_path(@comment.article_id)
	end


	private

	def comment_params
		params[:comment].permit(:body, :article_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/articles/edit.html.erb
<h2>Edit article</h2>

<%= form_for @article do |f| %>

	<%= f.label :title %><br/>
	<%= f.text_field :title %><br/><br/>
	<%= f.label :body %><br/>
	<%= f.text_area :body %><br/><br/>
	<%= f.label :select_categories %><br/>	
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br/>

	<%= f.submit %>	

<% end %>

app/views/articles/index.html.erb
<br/><br/>
<%= link_to "Articles by category", categories_path %> 
<%= link_to "My Articles", "/articles/my_articles"%>
<br/><br/><%= link_to "Add Article", new_article_path %><br/><br/>

<ol>
	<% @article.each do |article| %>
		<li><%= link_to article.title, article_path(article.id) %></li>
	<% end %>
</ol> 

app/views/articles/my_articles.html.erb
<ol>
<% @myarticles.each do |article|%>
<li><%= link_to article.title, article_path(article.id) %></li>
<%end%>
</ol>

app/views/articles/new.html.erb
<h2>Add new article</h2>

<%= form_for @article do |f| %>

	<%= f.label :title %><br/>
	<%= f.text_field :title %><br/><br/>
	<%= f.label :body %><br/>
	<%= f.text_area :body %><br/><br/>
	<%= f.label :select_categories %><br/>	
	<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br/>


	<%= f.submit %>	

<% end %>

app/views/articles/show.html.erb
<h2><%= @article.title %></h2>
<%= @article.body %><br/>
<% if @article.user_id == current_user.id %>
	<%= link_to "Edit article", edit_article_path(@article.id) %>
	<%= link_to "Delete article", article_path(@article.id), method: :delete, data: {confirm: "Are you sure"} %>
<% end %>

<br/><br/><b>Comments</b>
<ol>
	<% @comments.each do |comment| %>
		<li><%= comment.body %></li>
		<% if comment.user_id == current_user.id %>
			<%= link_to "Delete", comments_path(comment.id), method: :delete, data: {confirm: "Are you sure"}  %>
		<% end %>
	<% end %>
</ol>

<b>Add comment</b>
<%= form_for @comment do |f| %>
	
		
	
	<%= f.text_area :body %>
	<%= f.hidden_field :article_id, :value => @article.id %><br/>




	<%= f.submit "Comment" %>
<% end %>
<br/>
<%= link_to "Back to articles", articles_path %>

app/views/categories/edit.html.erb
<h2>Edit category</h2>
<%= form_for @category do |f| %>
	<br/>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>

	<%= f.submit "Add category" %>

<% end %> 

app/views/categories/index.html.erb
<h3>Select category</h3>
<%= link_to "All articles", articles_path %><br/><br/>
<%= link_to "Add category", new_category_path %>

<ol>
	<% @categories.each do |category| %>
		<li><%= link_to category.name, category_path(category.id) %><br/><%= link_to "Edit", edit_category_path(category.id) %>|<%= link_to "Delete", category_path(category.id), method: :delete, data: {confirm: "Are you sure"} %></li><br/>
	<% end %>
</ol>

app/views/categories/new.html.erb
<h2>Add new category</h2>
<%= link_to "Show categories", categories_path %><br/>

<%= form_for @category do |f| %>
	<br/>	
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>

	<%= f.submit "Add category" %>

<% end %> 

app/views/categories/show.html.erb
<h2>Articles by category</h2>
<%= link_to "View categories", categories_path %><br/><br/>
<%= @category.name %>
<ol>
	<% @category.articles.each do |article| %>
		<li><%= link_to article.title, article_path(article.id) %></li>
	<% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
Welcome <%= current_user.email %>
<%= link_to "Account Setting", edit_user_registration_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Login", new_user_session_path %>
<%= link_to "Register", new_user_registration_path %>
<% end %>

<%= alert %>

<%= notice %>

<%= yield %>

</body>
</html>